### ISSUE TITLE
issue in getting started guide for a windows maschine

### ISSUE THREAD

**Issue by Solarpirat** [V2GClarity/RISE-V2G#15]
Section "Using TLS And Certificates for XML Signatures"
It is not possible so create any cert on a Windows maschine just by rename the "generateCertificates.sh" to "generateCertificates.bat".

the shellskript have to be changed as following:

- rename in .bat
- delete all comments
- delete the parameter "-p" in the lines where the folders will be created 
- replace the parameter variables of the validity of the certs in the command lines into the values which are defined at the beginning of the script
- change all lines with the "cat" command to the MS-DOS equivalent "copy /b" and change the syntax of the folder structure from "/" to \

Example, before:
 cat certs/cpoSubCA2.pem certs/cpoSubCA1.pem > certs/intermediateCPOCAs.pem

after:
copy /b certs\cpoSubCA2.pem + certs\cpoSubCA1.pem  certs\intermediateCPOCAs.pem

**Comment by MarcMueltin** [comment]
Thanks for the hint!
I added now the equivalent .bat files in commit d8c9fc7. 
Slight changes:
- The comments are still there, using the REM command for comments
- The variables are still there, just the syntax for declaring and using variables needed to be adjusted for Windows
- Used the type command instead of copy /b
