### ISSUE TITLE
trusted_ca_keys and ocsp support

### ISSUE THREAD

**Issue by kakaniuniu** [V2GClarity/RISE-V2G#40]
Hello:

When establishing TLS connection, I got fatal error on the RISE-V2G(SECC) side. And I think this is because the TLS library of RISE-V2G(SECC) didn't support trusted_ca_keys and ocsp extensions in the client_hello message. Am I right? 
RISE-V2G(SECC) has done the interoperability with verisco test. Is it mean it is not the necessary to support trusted_ca_keys and ocsp support on EVCC side?

**Comment by MarcMueltin** [comment]
That's right, so far RISE V2G does not support the trusted_ca_keys and status_request_v2 (OCSP multi-stapling) extension for the TLS handshake. Simply because Java 8 does not support this feature. I have plans to migrate RISE V2G to Java 11 (the next Java version with long term support), but didn't find the time yet for it. I hope I'll be able to do this by the end of this year. 

I'll keep you posted.
