### ISSUE TITLE
session pause on EVCC for Pmax = 0

### ISSUE THREAD

**Issue by kakaniuniu** [V2GClarity/RISE-V2G#42]
Dear Marc,
I found that in 15118-4, there are a lot of test case about the session pause on EVCC if Pmax = 0, but I didn't find the process in RISE_V2G, I note RISE_V2G has already pass the verisco test, so is it(session pause on EVCC if Pmax = 0) not the necessary case?

for example:TC_EVCC_DC_VTB_PaymentServiceSelection_011
"Test System executes GoodCase procedure and waits for a paused V2G communication
session by receiving a SessionStopReq message with the current SessionID,
ChargingSession 'Pause' and all additional mandatory parameters (Test System has
sent a PmaxScheduleList with the first Pmax element = 0W (par_SECC_Pmax0W) within
ChargeParameterDiscoveryRes message before). After sending of a valid
SessionStopRes message, Test System waits for termination of the logical network by
the SUT, still detecting CP State B within the entire sleep mode. After
'par_SECC_Pmax0W' the SUT resumes the previously paused session by initiating a BCB
toggle. Furthermore Test System waits for successful link detection (old logical
network parameter) triggered by the SUT. Test System executes GoodCase procedure
and sends a ServiceDiscoveryRes message with the current SessionID, ResponseCode
'Ok', PaymentOption 'Contract' and 'ExternalPayment', valid
SupportedEnergyTransferMode and all additional mandatory parameters.
Test System then checks that the SUT sends a correct PaymentServiceSelectionReq
message with the current SessionID, the previous SelectedPaymentOption, valid
ServiceID and all additional mandatory parameters."

**Comment by MarcMueltin** [comment]
Hello @kakaniuniu, 
there is no requirement in ISO 15118-2 that would state that an EVCC must initiate a session pause if Pmax = 0. This is a behavior you might expect from an EV, but it's not mandated by any requirement. 

But I will check with the guys who wrote ISO 15118-4 if they really think this test case is valid.
The actual trigger for the pausing is the EVCC sending a SessionStopReq with field ChargingSession set to "Pause". The test system tries to trigger this behavior by setting the PMax element to 0 kW. Whether or not it is considered a false implementation if the EV does not react with pausing a charging session is something we need to discuss. 

I'll get back to you on this.

**Comment by MarcMueltin** [comment]
Hey @kakaniuniu,
Here's the answer I received from the creators of the test case you mentioned:

"The testability of the Sleep Mode is not always trivial and requires good insight into the functionality of the SUT (system under test). For this reason, three different approaches for EVCC tests have been defined within the scope of standardization:

- EVCC initiates charging pause without influence of the charging station (e.g. by configuration by the user)
- EVCC initiates charge pause due to charge plan with PMax = 0 in first schedule entry => charge pause is triggered immediately (charge loop is skipped)
- EVCC initiates charging pause due to charging plan with PMax = 0 in second schedule entry => EV charges for the duration of the first schedule entry and triggers charging pause after expiration of this first schedule entry

As you have already correctly mentioned, there is no exact specification in the standard when a corresponding loading pause should be initiated. For this reason we thought about different possible scenarios to increase the probability to test a pause. However, it is now also possible that none of the approaches will work. In this case the corresponding test cases would not be '_fail_', but '_not applicable_'."

So, RISE V2G works correctly according to the standard. However, I could implement a charging pause if the first schedule entry is set to 0 kW. But then also the question arises: how long should this schedule entry with 0 kW be at least to trigger a charging pause? 1 min? 5 min? less?
I think as long as this has not been formally decided, I'll keep the implementation as-is.
