### ISSUE TITLE
15118-2/Ed2 support

### ISSUE THREAD

**Issue by holzbuechse** [V2GClarity/RISE-V2G#43]
Dear Marc,

Looking at the code, it seems to me that the second edition of the ISO 15118-2 is not supported yet. To be more specific, I couldn't find the implementation of the 2016 message namespace ("iso:15118:2:2016"), which I think is the equivalent to the 15118-2/Ed2 or "ISO2". Is my assumption correct? If yes, do you plan to implement this second edition in the near future or will you skip it and wait for a newer edition to be published?

This topic is critical to me, as I am using your SECC application as a test reference for my own V2G client implementation. It is very convenient not to need a dedicated PLC connection/implementation for testing. Therefore I would like to thank you for this open source project! It would be a shame if I could not continue using it for this purpose.

**Comment by MarcMueltin** [comment]
Hi @holzbuechse, there is no second edition of ISO 15118-2 yet. The work on the second edition will start this May. I know that for some reason, which I don't really understand, there seems to be a new document of ISO 15118-2. But it is identical in content to the ISO 15118-2 document released in April 2014. So don't worry, RISE V2G is the most up-to-date implementation of ISO 15118-2.

I will implement the second edition in the future, but it will be a different open-source project based in Python (probably called RISE V2G 2.0). That project will also include the next version ISO 15118-20, which will be available end of 2020.

**Comment by lucasvanlierop** [comment]
Dear @MarcMueltin, I just started to create a CCS compatible EVCC (EV Charge Controller) (I need it for my converted car and it seems no one offers such thing yet) It's very helpful to see what you have already programmed, so thanks for that!

I'm planning to write my EVCC application in Kotlin (native). So of course I thought: "It would be so great if there would be a version of the RISE-V2G project in Kotlin!" 

May I ask why have chosen to switch to Python and have you maybe considered Kotlin? The reason I chose this language is because it is because it's a more modern language than Java and it can be compiled to both Java bytecode and native platforms (and even Javascript). Also IntelliJ can convert existing Java code to Kotlin.

FYI I also program in Python I don't enjoy it that much.

Love to hear your considerations and I would also like to add that if I able to use your library in my project I would like to contribute to it e.g: documentation, unit tests.

**Comment by MarcMueltin** [comment]
Dear @lucasvanlierop, in my opinion, Python is way easier to implement and to understand. The next version of ISO 15118-2 (Edition 2) and all further ISO 15118 open-source implementations will be part of a bigger project I have in mind, and I want to go this route with Python. Also, a survey I did among my newsletter subscribers showed overwhelming support for and demand of Python (> 95% for Python). Having said this, I cannot offer an open-source solution for more than one programming language, there's simply not enough time and resources available for this.

**Comment by lucasvanlierop** [comment]
Hi Marc, sorry for the late reply.

I totally understand you can't support maintaining multiple versions of the software, if most of your followers prefer Python then Python it is I guess ;)

In the meantime I'll just continue with my project and see what you come up with.I'm very curious what the bigger project is!
